# Generated by Django 3.0.5 on 2020-08-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=20)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('email', models.CharField(default='', max_length=50)),
                ('rentquote', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
